module.exports = {
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SALES_REPRESENTATIVE_EMAIL: process.env.SALES_REPRESENTATIVE_EMAIL,
  SENDGRID_PASSWORD: process.env.SENDGRID_PASSWORD,
  SENDGRID_USERNAME: process.env.SENDGRID_USERNAME
};